### ISSUE TITLE
feat: Improving the arrangement of the Gallery part in the main page.

### ISSUE THREAD

**Issue by Sahil-K123** [Sundar-Clinic/Main-Website#71]
**The Gallery part is having space to the left. Which is not looking good**.
It can be improved by displaying three images overthere.

**Screenshot**
![Screenshot 2023-10-01 004653](https://github.com/Sundar-Clinic/Main-Website/assets/123640518/8ea585e9-e993-40a4-9114-5b9f595ed701)

**Comment by Sahil-K123** [comment]
@kunalkeshan , can i work on this feature.

**Comment by kunalkeshan** [comment]
Hey @Sahil-K123 sure, thanks!

I thought it was a one time issue and didn't reload and check because it was not showing up in gallery page. 

Thanks for brining this up, appreciate the help.
