### ISSUE TITLE
Add Localization

### ISSUE THREAD

**Issue by sundarclinic** [Sundar-Clinic/Main-Website#81]

**Comment by kunalkeshan** [comment]
Needs to be split into two parts 

- https://github.com/Sundar-Clinic/Main-Website/issues/82
- https://github.com/Sundar-Clinic/Main-Website/issues/83

**Comment by kunalkeshan** [comment]
Will be added along with static content localization

- https://github.com/Sundar-Clinic/Main-Website/issues/86

**Comment by kunalkeshan** [comment]
Note: Fork from `feat/static-routing` branch and open a PR back to the same branch `feat/static-routing`.
